# Default values for graph-query-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "false"
replicaCount: 2
image:
  repository: coco/graph-query-api
  version: "" # should be set explicitly at installation
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 64Mi
  limits:
    memory: 256Mi
